###
# This is the place to override the php cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "php/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
node[:deploy].each do |application, deploy|
  app_root = "#{deploy[:deploy_to]}/current"
  execute "chmod -R 755 #{app_root}" do
  end
end